version: "3"
services:
  api:
    image: golang:1.15
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 12380:80
    tty: true
    volumes:
      - ./api:/app
    working_dir: /app
    command: "go run main.go"

  mysql:
    image: mysql:5.6
    command: ["mysqld", "--character-set-server=utf8mb4"]
    environment:
      MYSQL_DATABASE: Go/Next
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - 12381:80