version: "3"
services:
  api:
    build: ./api/docker 
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./api:/app
    working_dir: /app
    command: "go run ./cmd/main.go"
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: example
      TZ: Asia/Tokyo