version: "3"
services:
  api:
    build: ./api 
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 8080:8080 #host:container
    tty: true
    volumes:
      - ./api:/app
    working_dir: /app
    command: "go run ."

  next:
    build: .
    volumes:
      - ./next:/opt/app
    command: sh -c "yarn dev"
    ports:
      - '3000:3000'