version: "3"
services:
  api:
    build: ./api 
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 8080:8080 #host:container
    tty: true
    volumes:
      - ./api:/app
    working_dir: /app
    command: "go run ."
    depends_on:
      - mongo

  next:
    build: .
    volumes:
      - ./next:/opt/app
    command: sh -c "npm run dev"
    ports:
      - '3000:3000'

  mongo:
    image: mongo:5.0.3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: example
      TZ: Asia/Tokyo